import { useState, useMemo } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { toast } from 'sonner'
import {
  ArrowLeft,
  Loader2,
  Sparkles,
  AlertTriangle,
  CheckCheck,
  Upload,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { useProject } from '@/contexts/ProjectContext'
import { useGoldenSetDetail } from '@/hooks/useGoldenSets'
import { EvalStatusBadge } from '@/components/evaluation/EvalStatusBadge'
import { QueryList } from '@/components/evaluation/QueryList'
import { QueryEditor } from '@/components/evaluation/QueryEditor'
import { ReviewToolbar } from '@/components/evaluation/ReviewToolbar'
import { ReviewableQueryCard } from '@/components/evaluation/ReviewableQueryCard'
import { ImportModal } from '@/components/evaluation/ImportModal'
import type { ReviewStatus } from '@/types/golden-set'

export default function GoldenSetEditorPage() {
  const { goldenSetId } = useParams<{ goldenSetId: string }>()
  const navigate = useNavigate()
  const { currentProject } = useProject()
  const projectId = currentProject?.id ?? null

  const {
    goldenSet,
    selectedQueryId,
    selectedQuery,
    isLoading,
    isGenerating,
    generationProgress,
    setSelectedQueryId,
    fetchGoldenSet,
    addQuery,
    updateQuery,
    deleteQuery,
    addSource,
    deleteSource,
    bulkReview,
  } = useGoldenSetDetail(projectId, goldenSetId ?? null)

  const [addingQuery, setAddingQuery] = useState(false)
  const [newQueryText, setNewQueryText] = useState('')
  const [reviewFilter, setReviewFilter] = useState<ReviewStatus | 'all'>('all')
  const [importOpen, setImportOpen] = useState(false)

  const handleAddQuery = async () => {
    if (!newQueryText.trim()) return
    try {
      await addQuery({ queryText: newQueryText.trim() })
      setNewQueryText('')
      setAddingQuery(false)
    } catch {
      toast.error('Failed to add query. Please try again.')
    }
  }

  // Determine if this golden set has auto-generated content (review mode)
  const hasAutoGenerated = useMemo(
    () => goldenSet?.queries.some((q) => q.sourceMethod === 'auto_generated' || q.sourceMethod === 'imported') ?? false,
    [goldenSet]
  )

  const pendingCount = useMemo(
    () => goldenSet?.queries.filter((q) => q.reviewStatus === 'pending').length ?? 0,
    [goldenSet]
  )

  const filteredQueries = useMemo(() => {
    if (!goldenSet) return []
    if (reviewFilter === 'all') return goldenSet.queries
    return goldenSet.queries.filter((q) => q.reviewStatus === reviewFilter)
  }, [goldenSet, reviewFilter])

  const handleBulkAcceptPending = async () => {
    if (!goldenSet) return
    const pendingIds = goldenSet.queries
      .filter((q) => q.reviewStatus === 'pending')
      .map((q) => q.id)
    if (pendingIds.length === 0) return
    await bulkReview({ action: 'accept', queryIds: pendingIds })
  }

  const handleUpdateReviewStatus = async (queryId: string, status: ReviewStatus) => {
    await updateQuery(queryId, { reviewStatus: status })
  }

  const handleUpdateText = async (queryId: string, text: string) => {
    await updateQuery(queryId, { queryText: text })
  }

  if (isLoading || !goldenSet) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    )
  }

  // Show generating progress inline
  if (isGenerating) {
    const progress = generationProgress
    const pct = progress && progress.totalWindows > 0
      ? Math.round((progress.completedWindows / progress.totalWindows) * 100)
      : 0

    return (
      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" onClick={() => navigate('/evaluation')}>
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <div className="flex-1">
            <h1 className="text-2xl font-bold">{goldenSet.name}</h1>
          </div>
        </div>
        <div className="max-w-lg mx-auto py-8 space-y-4 text-center">
          <Sparkles className="h-8 w-8 text-primary animate-pulse mx-auto" />
          <h2 className="text-lg font-semibold">Generating Queries...</h2>
          <div className="space-y-2">
            <div className="flex justify-between text-sm text-muted-foreground">
              <span>{progress?.completedWindows ?? 0} / {progress?.totalWindows ?? '?'} windows</span>
              <span>{pct}%</span>
            </div>
            <div className="h-2 rounded-full bg-muted overflow-hidden">
              <div
                className="h-full rounded-full bg-primary transition-all duration-500"
                style={{ width: `${pct}%` }}
              />
            </div>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Button
          variant="ghost"
          size="icon"
          onClick={() => navigate('/evaluation')}
        >
          <ArrowLeft className="h-4 w-4" />
        </Button>
        <div className="flex-1">
          <div className="flex items-center gap-3">
            <h1 className="text-2xl font-bold">{goldenSet.name}</h1>
            <EvalStatusBadge status={goldenSet.status} />
          </div>
          <p className="text-sm text-muted-foreground">
            {goldenSet.queryCount} queries &middot;{' '}
            {goldenSet.documentCount} documents
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button
            size="sm"
            variant="outline"
            onClick={() => setImportOpen(true)}
          >
            <Upload className="mr-2 h-4 w-4" />
            Import
          </Button>
          <Button
            size="sm"
            variant="outline"
            onClick={() => navigate(`/evaluation/golden-sets/${goldenSetId}/generate`)}
          >
            <Sparkles className="mr-2 h-4 w-4" />
            Auto-Generate
          </Button>
        </div>
      </div>

      {/* Save gate warning */}
      {hasAutoGenerated && pendingCount > 0 && (
        <div className="flex items-center gap-3 rounded-lg border border-amber-200 bg-amber-50 dark:border-amber-900/50 dark:bg-amber-950/20 p-3">
          <AlertTriangle className="h-4 w-4 text-amber-600 shrink-0" />
          <p className="text-sm text-amber-800 dark:text-amber-300">
            <span className="font-medium">{pendingCount} queries pending review.</span>{' '}
            Review all queries before marking this golden set as completed.
          </p>
        </div>
      )}

      {/* Review mode: toolbar + card list */}
      {hasAutoGenerated ? (
        <div className="space-y-4">
          <div className="flex items-center justify-between gap-4">
            <ReviewToolbar
              queries={goldenSet.queries}
              activeFilter={reviewFilter}
              onFilterChange={setReviewFilter}
            />
            {pendingCount > 0 && (
              <Button
                size="sm"
                variant="outline"
                onClick={handleBulkAcceptPending}
              >
                <CheckCheck className="mr-2 h-4 w-4" />
                Accept All Pending
                <Badge variant="secondary" className="ml-2 text-xs">
                  {pendingCount}
                </Badge>
              </Button>
            )}
          </div>

          <div className="space-y-3">
            {filteredQueries.length === 0 ? (
              <p className="text-sm text-muted-foreground text-center py-8">
                No queries match this filter.
              </p>
            ) : (
              filteredQueries.map((q) => (
                <ReviewableQueryCard
                  key={q.id}
                  query={q}
                  onUpdateReviewStatus={handleUpdateReviewStatus}
                  onUpdateText={handleUpdateText}
                  onDelete={deleteQuery}
                />
              ))
            )}
          </div>
        </div>
      ) : (
        /* Manual mode: two-column layout */
        <div className="grid grid-cols-[320px_1fr] gap-6 min-h-[500px]">
          {/* Left: Query list */}
          <QueryList
            queries={goldenSet.queries}
            selectedId={selectedQueryId}
            onSelect={setSelectedQueryId}
            onAdd={() => setAddingQuery(true)}
          />

          {/* Right: Query editor */}
          <div className="border rounded-lg p-4">
            {addingQuery ? (
              <div className="space-y-3">
                <h3 className="text-sm font-medium">New Query</h3>
                <Input
                  value={newQueryText}
                  onChange={(e) => setNewQueryText(e.target.value)}
                  placeholder="Enter query text..."
                  autoFocus
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && !e.shiftKey) {
                      e.preventDefault()
                      handleAddQuery()
                    }
                  }}
                />
                <div className="flex gap-2">
                  <Button size="sm" onClick={handleAddQuery} disabled={!newQueryText.trim()}>
                    Add
                  </Button>
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => {
                      setAddingQuery(false)
                      setNewQueryText('')
                    }}
                  >
                    Cancel
                  </Button>
                </div>
              </div>
            ) : selectedQuery ? (
              <QueryEditor
                query={selectedQuery}
                projectId={projectId!}
                onUpdateText={(qId, text) =>
                  updateQuery(qId, { queryText: text })
                }
                onUpdateReferenceAnswer={(qId, answer) =>
                  updateQuery(qId, { referenceAnswer: answer })
                }
                onDelete={deleteQuery}
                onAddSource={addSource}
                onDeleteSource={deleteSource}
              />
            ) : (
              <div className="flex flex-col items-center justify-center h-full text-muted-foreground">
                <p>Select a query or add a new one.</p>
              </div>
            )}
          </div>
        </div>
      )}

      {projectId && goldenSetId && (
        <ImportModal
          open={importOpen}
          onOpenChange={setImportOpen}
          projectId={projectId}
          goldenSetId={goldenSetId}
          onImportComplete={fetchGoldenSet}
        />
      )}
    </div>
  )
}
