import { useState, useRef, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { toast } from 'sonner'
import { ArrowLeft, Loader2, Sparkles, Upload } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useProject } from '@/contexts/ProjectContext'
import { useGoldenSetDetail } from '@/hooks/useGoldenSets'
import { EvalStatusBadge } from '@/components/evaluation/EvalStatusBadge'
import { QueryList } from '@/components/evaluation/QueryList'
import { QueryEditor } from '@/components/evaluation/QueryEditor'
import { AutoGenerateDialog } from '@/components/evaluation/AutoGenerateDialog'
import { ImportModal } from '@/components/evaluation/ImportModal'
import * as api from '@/api/golden-sets'

export default function GoldenSetEditorPage() {
  const { goldenSetId } = useParams<{ goldenSetId: string }>()
  const navigate = useNavigate()
  const { currentProject } = useProject()
  const projectId = currentProject?.id ?? null

  const {
    goldenSet,
    selectedQueryId,
    selectedQuery,
    isLoading,
    setSelectedQueryId,
    fetchGoldenSet,
    addQuery,
    updateQuery,
    deleteQuery,
    addSource,
    deleteSource,
  } = useGoldenSetDetail(projectId, goldenSetId ?? null)

  const [importOpen, setImportOpen] = useState(false)
  const [autoGenerateOpen, setAutoGenerateOpen] = useState(false)
  const [editingName, setEditingName] = useState(false)
  const [nameValue, setNameValue] = useState('')
  const nameInputRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    if (editingName) nameInputRef.current?.focus()
  }, [editingName])

  const handleNameClick = () => {
    if (!goldenSet) return
    setNameValue(goldenSet.name)
    setEditingName(true)
  }

  const handleNameSave = async () => {
    const trimmed = nameValue.trim()
    if (!trimmed || !projectId || !goldenSetId) {
      setEditingName(false)
      return
    }
    if (trimmed !== goldenSet?.name) {
      try {
        await api.updateGoldenSet(projectId, goldenSetId, { name: trimmed })
        await fetchGoldenSet()
      } catch {
        toast.error('Failed to rename golden set.')
      }
    }
    setEditingName(false)
  }

  const handleAddQuery = async (queryText: string) => {
    try {
      await addQuery({ queryText })
    } catch {
      toast.error('Failed to add query. Please try again.')
    }
  }

  if (isLoading || !goldenSet) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    )
  }

  return (
    <div className="flex flex-col h-full gap-4">
      {/* Header */}
      <div className="flex items-center gap-4 shrink-0">
        <Button variant="ghost" size="icon" onClick={() => navigate('/evaluation')}>
          <ArrowLeft className="h-4 w-4" />
        </Button>
        <div className="flex-1">
          <div className="flex items-center gap-3">
            {editingName ? (
              <input
                ref={nameInputRef}
                value={nameValue}
                onChange={(e) => setNameValue(e.target.value)}
                onBlur={handleNameSave}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') handleNameSave()
                  if (e.key === 'Escape') setEditingName(false)
                }}
                className="text-2xl font-bold bg-transparent border-b border-primary outline-none w-full"
              />
            ) : (
              <h1
                className="text-2xl font-bold cursor-pointer hover:opacity-70 transition-opacity"
                onClick={handleNameClick}
              >
                {goldenSet.name}
              </h1>
            )}
            <EvalStatusBadge status={goldenSet.status} />
          </div>
          <p className="text-sm text-muted-foreground">
            {goldenSet.queryCount} queries &middot; {goldenSet.documentCount} documents
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button size="sm" variant="outline" onClick={() => setImportOpen(true)}>
            <Upload className="mr-2 h-4 w-4" />
            Import
          </Button>
          <Button size="sm" variant="outline" onClick={() => setAutoGenerateOpen(true)}>
            <Sparkles className="mr-2 h-4 w-4" />
            Auto-Generate
          </Button>
        </div>
      </div>

      {/* Two-column layout */}
      <div className="grid grid-cols-[300px_1fr] gap-6 flex-1 min-h-0">
        {/* Left: Query list */}
        <QueryList
          queries={goldenSet.queries}
          selectedId={selectedQueryId}
          onSelect={setSelectedQueryId}
          onAdd={handleAddQuery}
        />

        {/* Right: Query editor */}
        <div className="border rounded-lg p-4 overflow-y-auto">
          {selectedQuery ? (
            <QueryEditor
              query={selectedQuery}
              projectId={projectId!}
              onUpdateText={(qId, text) => updateQuery(qId, { queryText: text })}
              onUpdateReferenceAnswer={(qId, answer) =>
                updateQuery(qId, { referenceAnswer: answer })
              }
              onDelete={deleteQuery}
              onAddSource={addSource}
              onDeleteSource={deleteSource}
            />
          ) : (
            <div className="flex flex-col items-center justify-center h-full text-muted-foreground">
              <p>Select a query or create a new one.</p>
            </div>
          )}
        </div>
      </div>

      {/* Dialogs */}
      {projectId && goldenSetId && (
        <>
          <ImportModal
            open={importOpen}
            onOpenChange={setImportOpen}
            projectId={projectId}
            goldenSetId={goldenSetId}
            onImportComplete={fetchGoldenSet}
          />
          <AutoGenerateDialog
            open={autoGenerateOpen}
            onOpenChange={setAutoGenerateOpen}
            projectId={projectId}
            goldenSetId={goldenSetId}
            initialQueryCount={goldenSet.queries.length}
            onComplete={fetchGoldenSet}
          />
        </>
      )}
    </div>
  )
}
